version: '3.7'

services:

    database:
        image: postgres:14.3-alpine
        container_name: database
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports:
            - "5432:5432"
        networks:
            - app_network

    php:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        container_name: php
        ports:
            - "9000:9000"
        volumes:
            - ./:/var/www
        depends_on:
            - database
        networks:
            - app_network
        logging:
            driver: "json-file"
            options:
                max-size: "50m"

    web:
        image: nginx:latest
        build:
            context: .
            dockerfile: ./docker/nginx/Dockerfile
        container_name: web
        working_dir: /etc/nginx/conf.d/
        ports:
            - '8051:80'
        volumes:
            - ./:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
        networks:
            - app_network
        logging:
            driver: "json-file"
            options:
                max-size: "50m"

networks:
  app_network:
    driver: bridge